-- V004: Seed standard units of measure (SAP/ISO reference, 54 categories, ~310 entries).
-- Uses ON CONFLICT DO NOTHING for idempotency.

INSERT INTO platform.unit_of_measure (code, iso_code, name, category) VALUES
-- ── Acceleration ─────────────────────────────────────────────────────────────
('MS2',  'MSK',  'Meter/Second squared',        'Acceleration'),
-- ── Acid/Base Capacity ────────────────────────────────────────────────────────
('C36',  'C36',  'Mol/Cubic meter',             'Acid/Base Capacity'),
('C38',  'C38',  'Mol/Liter',                   'Acid/Base Capacity'),
('V02',  'C36',  'Milimol/Liter',               'Acid/Base Capacity'),
-- ── Amount of Substance ───────────────────────────────────────────────────────
('MMO',  'C18',  'Millimol',                    'Amount of Substance'),
('MOL',  'C34',  'Mol',                         'Amount of Substance'),
('B45',  'B45',  'Kilomol',                     'Amount of Substance'),
-- ── Area ─────────────────────────────────────────────────────────────────────
('GLM',  NULL,   'Gallons per mile (US)',        'Area'),
('MI2',  'MIK',  'Square mile',                 'Area'),
('LHK',  NULL,   'Liter/100 km',                'Area'),
('ACR',  'ACR',  'Acre',                        'Area'),
('HAR',  'HAR',  'Hectare',                     'Area'),
('YD2',  'YDK',  'Square yard',                 'Area'),
('MM2',  NULL,   'Square millimeter',           'Area'),
('PTS',  'PTS',  'Points (Area)',                'Area'),
('CM2',  'CMK',  'Square centimeter',           'Area'),
('KM2',  'KMK',  'Square kilometer',            'Area'),
('FT2',  'FTK',  'Square foot',                 'Area'),
('M2',   'MTK',  'Square meter',                'Area'),
('IN2',  'INK',  'Square inch',                 'Area'),
-- ── Density ──────────────────────────────────────────────────────────────────
('MGL',  'M1',   'Milligram/Liter',             'Density'),
('MGQ',  'GP',   'Milligram/Cubic meter',       'Density'),
('UGL',  NULL,   'Microgram/Liter',             'Density'),
('GLI',  'GL',   'Gram/Liter',                  'Density'),
('B34',  'B34',  'Kilogram/Cubic decimeter',    'Density'),
('tgl',  NULL,   'US Tonne/US gallon',          'Density'),
('KGV',  'KMQ',  'Kilogram/Cubic meter',        'Density'),
('kgb',  NULL,   'Kilogram/US barrel',          'Density'),
('kgg',  NULL,   'Kilogram/US gallon',          'Density'),
('TKL',  NULL,   'TKL',                         'Density'),
('tm3',  NULL,   'Tonne/1000 cubic meters',     'Density'),
('RHO',  '23',   'Gram/Cubic centimeter',       'Density'),
('GQ',   'GQ',   'Microgram/Cubic meter',       'Density'),
('A93',  'A93',  'Gram/Cubic meter',            'Density'),
('tMb',  NULL,   'Tonne/Million US barrel',     'Density'),
('tMs',  NULL,   'Tonne/Mil. standard cubic feet', 'Density'),
('lbg',  'GE',   'US Pound/US gallon',          'Density'),
('tbl',  NULL,   'Tonne/US barrel',             'Density'),
('lbs',  NULL,   'US Pound/Standard cubic foot','Density'),
('D41',  'D41',  'Ton/Cubic meter',             'Density'),
-- ── Digital Information ───────────────────────────────────────────────────────
('AD',   'AD',   'Byte',                        'Digital Information'),
('2P',   '2P',   'Kilobyte',                    'Digital Information'),
('4L',   '4L',   'Megabyte',                    'Digital Information'),
('E34',  'E34',  'Gigabyte',                    'Digital Information'),
('E35',  'E35',  'Terabyte',                    'Digital Information'),
('E36',  'E36',  'Petabyte',                    'Digital Information'),
('E64',  'E64',  'Kibibyte',                    'Digital Information'),
('E63',  'E63',  'Mebibyte',                    'Digital Information'),
('E62',  'E62',  'Gibibyte',                    'Digital Information'),
-- ── Dose Rate ────────────────────────────────────────────────────────────────
('SVH',  NULL,   'Sievert/Hour',                'Dose Rate'),
('SVS',  NULL,   'Sievert/Second',              'Dose Rate'),
('MSH',  NULL,   'Millisievert/Hour',           'Dose Rate'),
('USH',  NULL,   'Microsievert/Hour',           'Dose Rate'),
-- ── Dust Explosion Ratio ──────────────────────────────────────────────────────
('MPZ',  NULL,   'Meterpascal/Second',          'Dust Explosion Ratio'),
('MBZ',  NULL,   'Meterbar/Second',             'Dust Explosion Ratio'),
-- ── Dynamic Viscosity ─────────────────────────────────────────────────────────
('PAS',  'C65',  'Pascal second',               'Dynamic Viscosity'),
('MPS',  'C24',  'Millipascal second',          'Dynamic Viscosity'),
-- ── Electric Current ─────────────────────────────────────────────────────────
('C39',  'C39',  'Nanoampere',                  'Electric Current'),
('A',    'AMP',  'Ampere',                      'Electric Current'),
('B84',  'B84',  'Microampere',                 'Electric Current'),
('KA',   'B22',  'Kiloampere',                  'Electric Current'),
('MA',   '4K',   'Milliampere',                 'Electric Current'),
-- ── Electric Tension ─────────────────────────────────────────────────────────
('V',    'VLT',  'Volt',                        'Electric Tension'),
('B78',  'B78',  'Megavolt',                    'Electric Tension'),
('KV',   'KVT',  'Kilovolt',                    'Electric Tension'),
('MV',   '2Z',   'Millivolt',                   'Electric Tension'),
-- ── Electrical Capacitance ───────────────────────────────────────────────────
('C41',  'C41',  'Nanofarad',                   'Electrical Capacitance'),
('F',    'FAR',  'Farad',                       'Electrical Capacitance'),
('4O',   '4O',   'Microfarad',                  'Electrical Capacitance'),
('4T',   '4T',   'Pikofarad',                   'Electrical Capacitance'),
('C10',  'C10',  'Millifarad',                  'Electrical Capacitance'),
-- ── Electrical Conductivity ───────────────────────────────────────────────────
('V01',  NULL,   'Microsiemens per centimeter', 'Electrical Conductivity'),
('D10',  'D10',  'Siemens per meter',           'Electrical Conductivity'),
-- ── Electrical Resistance ─────────────────────────────────────────────────────
('B75',  'B75',  'Megohm',                      'Electrical Resistance'),
('A87',  'A87',  'Gigaohm',                     'Electrical Resistance'),
('KOH',  'B49',  'Kiloohm',                     'Electrical Resistance'),
('OHM',  'OHM',  'Ohm',                         'Electrical Resistance'),
-- ── Energy ───────────────────────────────────────────────────────────────────
('J',    'JOU',  'Joule',                       'Energy'),
('KWH',  'KWH',  'Kilowatt hours',              'Energy'),
('MJ',   'C15',  'Milijoule',                   'Energy'),
('KJ',   'KJ0',  'Kilojoule',                   'Energy'),
('GJ',   'GV',   'Gigajoule',                   'Energy'),
('MEJ',  '3B',   'Megajoule',                   'Energy'),
('MWH',  'MWH',  'Megawatt hour',               'Energy'),
-- ── Force ────────────────────────────────────────────────────────────────────
('N',    'NEW',  'Newton',                      'Force'),
('B47',  'B47',  'Kilonewton',                  'Force'),
('B73',  'B73',  'Meganewton',                  'Force'),
-- ── Frequency ────────────────────────────────────────────────────────────────
('PMI',  NULL,   '1/Minute',                    'Frequency'),
('MHZ',  'MHZ',  'Megahertz',                   'Frequency'),
('KHZ',  'KHZ',  'Kilohertz',                   'Frequency'),
('HZ',   'HTZ',  'Hertz (1/second)',             'Frequency'),
-- ── Heat Conductivity ─────────────────────────────────────────────────────────
('WMK',  'D53',  'Heat Conductivity',           'Heat Conductivity'),
-- ── Hydrolysis Rate ───────────────────────────────────────────────────────────
('LMS',  NULL,   'Liter/Molsecond',             'Hydrolysis Rate'),
-- ── Inverse Area ─────────────────────────────────────────────────────────────
('M2I',  NULL,   '1/Square meter',              'Inverse Area'),
-- ── Kinematic Viscosity ───────────────────────────────────────────────────────
('22S',  NULL,   'Square millimeter/second',    'Kinematic Viscosity'),
('M2S',  'S4',   'Square meter/second',         'Kinematic Viscosity'),
-- ── Length ───────────────────────────────────────────────────────────────────
('MIM',  '4H',   'Micrometer',                  'Length'),
('M',    'MTR',  'Meter',                       'Length'),
('CM',   'CMT',  'Centimeter',                  'Length'),
('DM',   'DMT',  'Decimeter',                   'Length'),
('FT',   'FOT',  'Foot',                        'Length'),
('NAM',  'C45',  'Nanometer',                   'Length'),
('YD',   'YRD',  'Yards',                       'Length'),
('IN',   'INH',  'Inch',                        'Length'),
('KM',   'KMT',  'Kilometer',                   'Length'),
('MI',   'SMI',  'Mile',                        'Length'),
('MM',   'MMT',  'Millimeter',                  'Length'),
-- ── Luminous Intensity ────────────────────────────────────────────────────────
('CD',   'CDL',  'Candela',                     'Luminous Intensity'),
-- ── Magnetic Field Density ────────────────────────────────────────────────────
('TES',  'D33',  'Tesla',                       'Magnetic Field Density'),
('MTE',  'C29',  'Millitesla',                  'Magnetic Field Density'),
-- ── Mass ─────────────────────────────────────────────────────────────────────
('OZ',   'ONZ',  'Ounce',                       'Mass'),
('G',    'GRM',  'Gram',                        'Mass'),
('TO',   'TNE',  'Tonne',                       'Mass'),
('TON',  NULL,   'US ton',                      'Mass'),
('KG',   'KGM',  'Kilogram',                    'Mass'),
('KT',   NULL,   'Kilotonne',                   'Mass'),
('LB',   'LBR',  'US pound',                    'Mass'),
('MG',   'MGM',  'Milligram',                   'Mass'),
-- ── Mass Coverage ────────────────────────────────────────────────────────────
('MGF',  NULL,   'Milligram/Square centimeter', 'Mass Coverage'),
('GM2',  'GM',   'Gram/Square meter',           'Mass Coverage'),
('THA',  NULL,   'THA',                         'Mass Coverage'),
('KGF',  '28',   'Kilogram/Square meter',       'Mass Coverage'),
-- ── Mass per Energy ───────────────────────────────────────────────────────────
('ttj',  NULL,   'Tonne/Terajoule',             'Mass per Energy'),
('MGJ',  NULL,   'MGJ',                         'Mass per Energy'),
('KGJ',  NULL,   'KGJ',                         'Mass per Energy'),
('kgj',  NULL,   'Kilogram/Joule',              'Mass per Energy'),
('tjl',  NULL,   'Tonne/Joule',                 'Mass per Energy'),
('lbb',  NULL,   'US Pound/British thermal unit','Mass per Energy'),
('lbm',  NULL,   'US Pound/Million BTU',        'Mass per Energy'),
('tbt',  NULL,   'Tonne/British thermal unit',  'Mass per Energy'),
-- ── Mass Proportion ───────────────────────────────────────────────────────────
('GKG',  'GK',   'Gram/Kilogram',               'Mass Proportion'),
('MGG',  NULL,   'Milligram/Gram',              'Mass Proportion'),
('MGK',  'NA',   'Milligram/Kilogram',          'Mass Proportion'),
('MGT',  NULL,   'MGT',                         'Mass Proportion'),
('KGK',  NULL,   'Kilogram/Kilogram',           'Mass Proportion'),
('KGT',  NULL,   'Kilogram/Tonne',              'Mass Proportion'),
('tt',   NULL,   'Tonne/Tonne',                 'Mass Proportion'),
('kgt',  NULL,   'Kilogram/US tonne',           'Mass Proportion'),
('TKT',  NULL,   'TKT',                         'Mass Proportion'),
('MPB',  NULL,   'Mass parts per billion',      'Mass Proportion'),
('MPM',  NULL,   'Mass parts per million',      'Mass Proportion'),
('MPT',  NULL,   'Mass parts per trillion',     'Mass Proportion'),
('Tot',  NULL,   'Tonne/US ton',                'Mass Proportion'),
('tot',  NULL,   'US Ton/US ton',               'Mass Proportion'),
('M%',   NULL,   'Percent mass',                'Mass Proportion'),
('GHG',  NULL,   'Gram/Hectogram',              'Mass Proportion'),
('lbt',  NULL,   'US Pound/US tonne',           'Mass Proportion'),
('M%O',  NULL,   'Permille mass',               'Mass Proportion'),
-- ── Miscellaneous Units ───────────────────────────────────────────────────────
('DEG',  'DD',   'Degree',                      'Miscellaneous'),
('BAG',  'BG',   'Bag',                         'Miscellaneous'),
('TEU',  'E22',  'Twenty-Foot Equiv. Unit',     'Miscellaneous'),
('DGP',  NULL,   'DGP',                         'Miscellaneous'),
('KWK',  NULL,   'kg act.ingrd. / kg',          'Miscellaneous'),
('ST',   'PCE',  'Piece',                       'Miscellaneous'),
('PAA',  'PR',   'Pair',                        'Miscellaneous'),
('CS',   'CS',   'Case',                        'Miscellaneous'),
('TH',   'MIL',  'Thousands',                   'Miscellaneous'),
('PAK',  'PK',   'Pack',                        'Miscellaneous'),
('KGW',  NULL,   'Kilogram act. ingrd.',        'Miscellaneous'),
('PAL',  'PF',   'Pallet',                      'Miscellaneous'),
('G/L',  NULL,   'gram act.ingrd / liter',      'Miscellaneous'),
('DR',   'DR',   'Drum',                        'Miscellaneous'),
('PRS',  'IE',   'Number of Persons',           'Miscellaneous'),
('DZ',   'DZN',  'Dozen',                       'Miscellaneous'),
('MLW',  NULL,   'Milliliter act. ingr.',        'Miscellaneous'),
('EA',   'EA',   'each',                        'Miscellaneous'),
('EE',   NULL,   'Enzyme Units',                'Miscellaneous'),
('EML',  NULL,   'Enzyme Units / Milliliter',   'Miscellaneous'),
('GAU',  NULL,   'Gram Gold',                   'Miscellaneous'),
('GRO',  'GRO',  'Gross',                       'Miscellaneous'),
('GW',   NULL,   'Gram act. ingrd.',             'Miscellaneous'),
('VAL',  NULL,   'Value-only material',         'Miscellaneous'),
('KI',   'CR',   'Crate',                       'Miscellaneous'),
('LE',   'C62',  'Activity unit',               'Miscellaneous'),
('LM',   NULL,   'Length in Metres per Unit',   'Miscellaneous'),
('BOT',  'BO',   'Bottle',                      'Miscellaneous'),
('ROL',  'RO',   'Role',                        'Miscellaneous'),
('KAN',  'CA',   'Canister',                    'Miscellaneous'),
('KAR',  'CT',   'Carton',                      'Miscellaneous'),
-- ── Molar Energy ─────────────────────────────────────────────────────────────
('KJM',  'B44',  'Kilojoule/Mol',               'Molar Energy'),
('JMO',  'B15',  'Joule/Mol',                   'Molar Energy'),
-- ── Particle Concentration ────────────────────────────────────────────────────
('TM3',  NULL,   '1/Cubic meter',               'Particle Concentration'),
('TC3',  NULL,   '1/Cubic centimeter',          'Particle Concentration'),
-- ── Permeability ─────────────────────────────────────────────────────────────
('PMR',  NULL,   'Permeation rate SI',          'Permeability'),
('PRM',  NULL,   'Permeation rate',             'Permeability'),
-- ── Points ───────────────────────────────────────────────────────────────────
('P',    NULL,   'Points',                      'Points'),
-- ── Power ────────────────────────────────────────────────────────────────────
('MGW',  'MAW',  'Megawatt',                    'Power'),
('KVA',  'KVA',  'Kilovoltampere',              'Power'),
('W',    'WTT',  'Watt',                        'Power'),
('KW',   'KWT',  'Kilowatt',                    'Power'),
('MW',   'C31',  'Milliwatt',                   'Power'),
('MVA',  'MVA',  'Megavoltampere',              'Power'),
('D46',  'D46',  'Voltampere',                  'Power'),
-- ── Pressure ─────────────────────────────────────────────────────────────────
('gjm',  NULL,   'Gigajoule/Cubic meter',       'Pressure'),
('PA',   'PAL',  'Pascal',                      'Pressure'),
('BAR',  'BAR',  'bar',                         'Pressure'),
('C56',  'C56',  'Newton/Square millimeter',    'Pressure'),
('bbl',  NULL,   'British thermal unit/US barrel', 'Pressure'),
('HPA',  'A97',  'Hectopascal',                 'Pressure'),
('mjm',  NULL,   'Megajoule/Cubik meter',       'Pressure'),
('PSI',  NULL,   'Pounds per square inch',      'Pressure'),
('bft',  'B0',   'British Thermal Unit/Cubic feet', 'Pressure'),
('bgl',  NULL,   'British Thermal Unit/US gallon', 'Pressure'),
('MPA',  'MPA',  'Megapascal',                  'Pressure'),
('MBA',  'MBR',  'Millibar',                    'Pressure'),
('jm3',  NULL,   'Joule/Cubic meter',           'Pressure'),
('mbb',  NULL,   'Million BTU/US barrel',       'Pressure'),
('mbg',  NULL,   'Million BTU/US gallon',       'Pressure'),
('mbm',  NULL,   'MMBtu/Mill. stand. cubic feet','Pressure'),
('KPA',  'KPA',  'Kilopascal',                  'Pressure'),
('mbs',  NULL,   'MMBtu/Standard cubic feet',   'Pressure'),
('gj3',  NULL,   'Gigajoule/1000 cubic meters', 'Pressure'),
('GJK',  NULL,   'GJK',                         'Pressure'),
-- ── Proportion ───────────────────────────────────────────────────────────────
('%',    'P1',   'Percentage',                  'Proportion'),
('1',    NULL,   'One',                         'Proportion'),
('ONE',  NULL,   'One',                         'Proportion'),
('PPB',  '61',   'Parts per billion',           'Proportion'),
('PPM',  '59',   'Parts per million',           'Proportion'),
('PPT',  NULL,   'Parts per trillion',          'Proportion'),
('%O',   NULL,   'Per mile',                    'Proportion'),
-- ── Radiation Efficiency ──────────────────────────────────────────────────────
('WMP',  NULL,   'Radiation efficiency',        'Radiation Efficiency'),
-- ── Radioactivity ────────────────────────────────────────────────────────────
('BQ',   NULL,   'Becquerel',                   'Radioactivity'),
('GBQ',  'GBQ',  'Gigabecquerel',               'Radioactivity'),
('MBQ',  '4N',   'Megabecquerel',               'Radioactivity'),
('TBQ',  NULL,   'Terabecquerel',               'Radioactivity'),
('KBQ',  '2Q',   'Kilobecquerel',               'Radioactivity'),
-- ── Rate of Temperature Change ────────────────────────────────────────────────
('KMN',  NULL,   'Kelvin/Minute',               'Rate of Temperature Change'),
('KMS',  NULL,   'Kelvin/Second',               'Rate of Temperature Change'),
-- ── Sound Pressure Level ──────────────────────────────────────────────────────
('DBA',  NULL,   'Decibel (A-weighted)',         'Sound Pressure Level'),
('DBC',  NULL,   'Decibel (C-weighted)',         'Sound Pressure Level'),
-- ── Specific Activity ─────────────────────────────────────────────────────────
('MBG',  NULL,   'MBG',                         'Specific Activity'),
('KBG',  NULL,   'KBG',                         'Specific Activity'),
('KBK',  'B25',  'Kilobecquerel/Kilogram',      'Specific Activity'),
('BQG',  NULL,   'BQG',                         'Specific Activity'),
('BQK',  'A18',  'Becquerel/Kilogram',          'Specific Activity'),
-- ── Specific Electrical Resistance ───────────────────────────────────────────
('OCM',  'C60',  'Spec. Elec. Resistance (Ohm cm)', 'Specific Electrical Resistance'),
('OM',   'C61',  'Spec. Elec. Resistance (Ohm m)',  'Specific Electrical Resistance'),
-- ── Specific Energy ───────────────────────────────────────────────────────────
('gjt',  NULL,   'Gigajoule/US tonne',          'Specific Energy'),
('MJK',  NULL,   'Megajoule/Kilogram',          'Specific Energy'),
('btl',  NULL,   'British Thermal Unit/US pound','Specific Energy'),
('kwk',  NULL,   'Kilowatt hours/Kilogram',     'Specific Energy'),
('KJG',  NULL,   'KJG',                         'Specific Energy'),
('KJK',  'B42',  'Kilojoule/Kilogram',          'Specific Energy'),
('JKG',  'J2',   'Joule/Kilogram',              'Specific Energy'),
('mbk',  NULL,   'Million BTU/Kilogram',        'Specific Energy'),
('mbt',  NULL,   'Million BTU/US tonne',        'Specific Energy'),
('GJT',  NULL,   'Gigajoule/Tonne',             'Specific Energy'),
-- ── Specific Equivalent ───────────────────────────────────────────────────────
('MMG',  NULL,   'Millimol/Gram',               'Specific Equivalent'),
('MOK',  'C19',  'Mol/Kilogram',                'Specific Equivalent'),
-- ── Specific Heat Capacity ────────────────────────────────────────────────────
('JKK',  'B11',  'Specific Heat Capacity',      'Specific Heat Capacity'),
-- ── Specific Surface (Mass) ───────────────────────────────────────────────────
('M2G',  NULL,   'Specific Surface (Mass)',     'Specific Surface (Mass)'),
('M2K',  'D21',  'Square meter per kilogram',   'Specific Surface (Mass)'),
-- ── Specific Surface (Volume) ─────────────────────────────────────────────────
('M2C',  NULL,   'M2C',                         'Specific Surface (Volume)'),
('M2M',  NULL,   'M2M',                         'Specific Surface (Volume)'),
-- ── Speed ────────────────────────────────────────────────────────────────────
('2M',   '2M',   'Centimeter/Second',           'Speed'),
('2X',   '2X',   'Meter/Minute',                'Speed'),
('MMA',  NULL,   'Millimeter/Year',             'Speed'),
('MMH',  NULL,   'Millimeter/Hour',             'Speed'),
('MMS',  'C16',  'Millimeter/Second',           'Speed'),
('M/S',  'MTS',  'Meter/Second',                'Speed'),
('CMH',  NULL,   'Centimeter/Hour',             'Speed'),
('KMH',  'KMH',  'Kilometer/Hour',              'Speed'),
('MTS',  'MTS',  'Meter/Hour',                  'Speed'),
-- ── Surface Contamination ─────────────────────────────────────────────────────
('MB2',  NULL,   'MB2',                         'Surface Contamination'),
('BM2',  NULL,   'BM2',                         'Surface Contamination'),
('KB2',  NULL,   'KB2',                         'Surface Contamination'),
('BQ2',  NULL,   'BQ2',                         'Surface Contamination'),
-- ── Surface Tension ───────────────────────────────────────────────────────────
('MNM',  'C22',  'Millinewton/Meter',           'Surface Tension'),
('NM',   '4P',   'Newton/Meter',                'Surface Tension'),
-- ── Temperature ──────────────────────────────────────────────────────────────
('K',    'KEL',  'Kelvin',                      'Temperature'),
('FA',   'FAH',  'Fahrenheit',                  'Temperature'),
('GC',   'CEL',  'Degrees Celsius',             'Temperature'),
-- ── Time ─────────────────────────────────────────────────────────────────────
('PS',   NULL,   'Picosecond',                  'Time'),
('STD',  'HUR',  'Hours',                       'Time'),
('H',    NULL,   'Hour',                        'Time'),
('MIN',  'MIN',  'Minute',                      'Time'),
('S',    'SEC',  'Second',                      'Time'),
('MIS',  'B98',  'Microsecond',                 'Time'),
('JHR',  'ANN',  'Years',                       'Time'),
('MON',  'MON',  'Months',                      'Time'),
('WCH',  'WEE',  'Weeks',                       'Time'),
('TAG',  'DAY',  'Days',                        'Time'),
('10',   'DAY',  'Days (alt.)',                  'Time'),
('MS',   'C26',  'Millisecond',                 'Time'),
('TST',  NULL,   'TST',                         'Time'),
('NS',   'C47',  'Nanosecond',                  'Time'),
('PDA',  NULL,   'Consulting Days',             'Time'),
-- ── Vaporization Speed ────────────────────────────────────────────────────────
('WTL',  NULL,   'Evaporation rate',            'Vaporization Speed'),
-- ── Volume ───────────────────────────────────────────────────────────────────
('CCM',  'CMQ',  'Cubic centimeter',            'Volume'),
('CTL',  'CLT',  'Centiliter',                  'Volume'),
('PT',   'PT',   'Pint, US liquid',             'Volume'),
('GLL',  'GLL',  'US gallon',                   'Volume'),
('CDM',  'DMQ',  'Cubic decimeter',             'Volume'),
('QT',   'QT',   'Quart, US liquid',            'Volume'),
('L',    'LTR',  'Liter',                       'Volume'),
('YD3',  'YDQ',  'Cubic yard',                  'Volume'),
('4G',   '4G',   'Microliter',                  'Volume'),
('MMQ',  'MMQ',  'Cubic millimeter',            'Volume'),
('HL',   'HLT',  'Hectoliter',                  'Volume'),
('FT3',  'FTQ',  'Cubic foot',                  'Volume'),
('M3',   'MTQ',  'Cubic meter',                 'Volume'),
('ML',   'MLT',  'Milliliter',                  'Volume'),
('IN3',  'INQ',  'Cubic inch',                  'Volume'),
('OZA',  'OZA',  'Fluid ounce US',              'Volume'),
-- ── Volume Rate of Flow ───────────────────────────────────────────────────────
('C3S',  '2J',   'Cubic centimeter/Second',     'Volume Rate of Flow'),
('sch',  NULL,   'Standard cubic feet/Hour',    'Volume Rate of Flow'),
('scy',  NULL,   'Standard cubic feet/Year',    'Volume Rate of Flow'),
('GPH',  NULL,   'Gallons/Hour (US)',            'Volume Rate of Flow'),
('MQH',  'MQH',  'Cubic meter/Hour',             'Volume Rate of Flow'),
('LPH',  NULL,   'Liter/Hour',                  'Volume Rate of Flow'),
('L2',   'L2',   'Liter/Minute',                'Volume Rate of Flow'),
('M3D',  NULL,   'Cubic meter/Day',             'Volume Rate of Flow'),
('M3S',  'MQS',  'Cubic meter/Second',          'Volume Rate of Flow')
ON CONFLICT (code) DO NOTHING;
