-- MES-9: Envers _aud tables for route + route_operation (ERR-MES-061).

CREATE TABLE routing.route_aud (
    id                                  UUID NOT NULL,
    rev                                 INT4 NOT NULL,
    revtype                             INT2,
    revend                              INTEGER REFERENCES routing.revinfo (rev),
    revend_tstmp                        TIMESTAMPTZ,
    org_id                              UUID,
    part_id                             UUID,
    part_revision                       VARCHAR(20),
    route_type_id                       UUID,
    bom_id                              UUID,
    bom_revision_id                     UUID,
    inspection_plan_revision_id         UUID,
    revision                            INTEGER,
    status                              VARCHAR(20),
    reason_for_revision                 VARCHAR(1000),
    bom_revision_superseded             BOOLEAN,
    inspection_plan_revision_superseded BOOLEAN,
    custom_fields                       JSONB,
    created_by                          VARCHAR(255),
    created_at                          TIMESTAMPTZ,
    modified_by                         VARCHAR(255),
    modified_at                         TIMESTAMPTZ,
    CONSTRAINT pk_route_aud     PRIMARY KEY (id, rev),
    CONSTRAINT fk_route_aud_rev FOREIGN KEY (rev) REFERENCES routing.revinfo (rev)
);

CREATE TABLE routing.route_operation_aud (
    id                          UUID NOT NULL,
    rev                         INT4 NOT NULL,
    revtype                     INT2,
    revend                      INTEGER REFERENCES routing.revinfo (rev),
    revend_tstmp                TIMESTAMPTZ,
    org_id                      UUID,
    route_id                    UUID,
    operation_number            INTEGER,
    sequence_number             INTEGER,
    description                 VARCHAR(500),
    optional                    BOOLEAN,
    osp                         BOOLEAN,
    significant_process_type_id UUID,
    supplier_id                 UUID,
    group_id                    UUID,
    clocking                    BOOLEAN,
    operation_revision          INTEGER,
    operation_status            VARCHAR(20),
    governing_route_revision    INTEGER,
    created_by                  VARCHAR(255),
    created_at                  TIMESTAMPTZ,
    modified_by                 VARCHAR(255),
    modified_at                 TIMESTAMPTZ,
    CONSTRAINT pk_route_operation_aud     PRIMARY KEY (id, rev),
    CONSTRAINT fk_route_operation_aud_rev FOREIGN KEY (rev) REFERENCES routing.revinfo (rev)
);
