package com.mes.udf.domain;

public enum ModuleKey {
    ITEM_MASTER, WORK_ORDER, ROUTING, RECEIVING, INVENTORY, BOM_LINE, BOM_HEADER, BOM_BROWSER,
    EMPLOYEE, SKILL, CERTIFICATION,
    INSPECTION_PLAN, INSPECTION_CHARACTERISTIC,
    WORK_INSTRUCTION, WORK_INSTRUCTION_STEP
}
